<?php
    include_once "components/google.phtml";
    include_once "components/yandex.phtml";
    include_once "components/navbar.phtml";
    switch ($second_page){
        case 'landing':
            include_once "components/services/landing.phtml";
            break;
        case 'business-site':
            include_once "components/services/business-site.phtml";
            break;
        case 'tilda':
            include_once "components/services/tilda.phtml";
            break;
        case 'logo':
            include_once "components/services/logo.phtml";
            break;
        case 'brandbook':
            include_once "components/services/brandbook.phtml";
            break;
        case 'form-style':
            include_once "components/services/form-style.phtml";
            break;
        case 'semantic-core':
            include_once "components/services/semantic-core.phtml";
            break;
        case 'smm':
            include_once "components/services/smm.phtml";
            break;
        case 'analysis':
            include_once "components/services/analysis.phtml";
            break;

        case 'mobile':
            include_once "components/services/mobile.phtml";
            break;
        case 'online-store':
            include_once "components/services/online-store.phtml";
            break;
        case 'promo-site':
            include_once "components/services/promo-site.phtml";
            break;
        case 'site-catalog':
            include_once "components/services/site-catalog.phtml";
            break;

        case 'label':
            include_once "components/services/label.phtml";
            break;
        case 'presentation':
            include_once "components/services/presentation.phtml";
            break;
        case 'print':
            include_once "components/services/print.phtml";
            break;

        case 'seo':
            include_once "components/services/seo.phtml";
            break;
        case 'advert':
            include_once "components/services/advert.phtml";
            break;
    }

    include_once "components/why.phtml";
    include_once "components/our_clients.phtml";
    include_once "components/contacts.phtml";
    include_once "components/more.phtml";

    switch ($second_page){
        case 'landing':
            include_once "components/services/landing_questions.phtml";
            include_once "components/services/landing_more_details_about.phtml";
            break;
        case 'business-site':
            include_once "components/services/business-site_questions.phtml";
            include_once "components/services/business-site_more_details_about.phtml";
            break;
        case 'tilda':
            include_once "components/services/tilda_questions.phtml";
            include_once "components/services/tilda_more_details_about.phtml";
            break;
        case 'logo':
            include_once "components/services/logo_questions.phtml";
            include_once "components/services/logo_more_details_about.phtml";
            break;
        case 'brandbook':
            include_once "components/services/brandbook_questions.phtml";
            include_once "components/services/brandbook_more_details_about.phtml";
            break;
        case 'form-style':
            include_once "components/services/form-style_questions.phtml";
            include_once "components/services/form-style_more_details_about.phtml";
            break;
        case 'semantic-core':
            include_once "components/services/semantic-core_questions.phtml";
            include_once "components/services/sematic-core_more_details_about.phtml";
            break;
        case 'smm':
            include_once "components/services/smm_questions.phtml";
            include_once "components/services/smm_more_details_about.phtml";
            break;
        case 'analysis':
            include_once "components/services/analysis_questions.phtml";
            include_once "components/services/analysis_more_details_about.phtml";
            break;

        case 'mobile':
            include_once "components/services/mobile_questions.phtml";
            include_once "components/services/mobile_more_details_about.phtml";
            break;
        case 'online-store':
            include_once "components/services/online-store_questions.phtml";
            include_once "components/services/online-store_more_details_about.phtml";
            break;
        case 'promo-site':
            include_once "components/services/promo-site_questions.phtml";
            include_once "components/services/promo-site_more_details_about.phtml";
            break;
        case 'site-catalog':
            include_once "components/services/site-catalog_questions.phtml";
            include_once "components/services/site-catalog_more_details_about.phtml";
            break;

        case 'label':
            include_once "components/services/label_questions.phtml";
            include_once "components/services/label_more_details_about.phtml";
            break;
        case 'presentation':
            include_once "components/services/presentation_questions.phtml";
            include_once "components/services/presentation_more_details_about.phtml";
            break;
        case 'print':
            include_once "components/services/print_questions.phtml";
            include_once "components/services/print_more_details_about.phtml";
            break;

        case 'seo':
            include_once "components/services/seo_questions.phtml";
            include_once "components/services/seo_more_details_about.phtml";
            break;
        case 'advert':
            include_once "components/services/advert_questions.phtml";
            include_once "components/services/advert_more_details_about.phtml";
            break;
    }

    include_once "components/footer.phtml";
