<div class="container current-service">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <img src="/img/Analisys.png" class="w-100">
        </div>
        <div class="col-lg-5 offset-lg-1">
            <h1 class="title mt-lg-0 mt-4"> Доработка сайта </h1>

            <p class="description pt-32">
                Анализ и доработка готового сайта включают в себя действия направленные на поиск ошибок и слабых мест сайта с последующим их исправлением. По мимо этого в услугу входит внутрянняя и внешняя SEO-оптимизация сайта
            </p>
            <div class="row mt-5">
                <div class="col-md-3">
                    <a class="btn btn-black" href="#contact">Сделать заказ</a>
                </div>
            </div>
        </div>
    </div>
</div>
