<div class="container current-service">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <img src="/img/Esclusiv_Style.png" class="w-100">
        </div>
        <div class="col-lg-5 offset-lg-1">
            <h1 class="title mt-lg-0 mt-4"> Фирменный стиль </h1>

            <p class="description pt-32">
                Фирменный стиль компании – это набор графических элементов и форм, концепция и стилистика которых является единой. Визуальный стиль позволяет донести нужную визуальную информацию до пользователей и сформировать связь с вашим брендом.
            </p>
            <div class="row mt-5">
                <div class="col-md-3">
                    <a class="btn btn-black" href="#contact">Сделать заказ</a>
                </div>
            </div>
        </div>
    </div>
</div>
