<div class="container current-service">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <img src="/img/Logo.png" class="w-100">
        </div>
        <div class="col-lg-5 offset-lg-1">
            <h1 class="title mt-lg-0 mt-4"> Логотип </h1>

            <p class="description pt-32">
                Логотип это графическое изображение, знак или символ, который используется в качестве инструмента для повышения узнаваемости компании среди конкурентов. Товарный знак это обязательная составляющая уникального стиля бренда. Он может присутствовать на различных видах одежды и рекламных материалах.
            </p>
            <div class="row mt-5">
                <div class="col-md-3">
                    <a class="btn btn-black" href="#contact">Сделать заказ</a>
                </div>
            </div>
        </div>
    </div>
</div>
