<div class="container current-service">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <img src="/img/SEO.png" class="w-100">
        </div>
        <div class="col-lg-5 offset-lg-1">
            <h1 class="title mt-lg-0 mt-4"> SEO-продвижение </h1>

            <p class="description pt-32">
                SEO-продвижение - это ряд действий, направленных на улучшение показателей веб-сайта в результатах поисковых систем. Сюда входят внутренняя и внешняя оптимизация сайта, анализ конкурентов, формирование структуры на основе данных семантического ядра.
            </p>
            <div class="row mt-5">
                <div class="col-md-3">
                    <a class="btn btn-black" href="#contact">Сделать заказ</a>
                </div>
            </div>
        </div>
    </div>
</div>
