<div class="container current-service">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <img src="/img/Brandbook.png" class="w-100">
        </div>
        <div class="col-lg-5 offset-lg-1">
            <h1 class="title mt-lg-0 mt-4"> Брендбук </h1>

            <p class="description pt-32">
                Брендбук - является документом, который содержит ряд правил компании для успешного позиционирования в бизнес сфере. Разработка уникального дизайна для брендбука является качественная интеграция фирменного стиля в корпоративную среду. Данный документ позволит упростить задачи связанные с продвижением и позиционированием компании на рынке.
            </p>
            <div class="row mt-5">
                <div class="col-md-3">
                    <a class="btn btn-black" href="#contact">Сделать заказ</a>
                </div>
            </div>
        </div>
    </div>
</div>
