<div class="container current-service">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <img src="/img/Site_Visit.png" class="w-100">
        </div>
        <div class="col-lg-5 offset-lg-1">
            <h1 class="title mt-lg-0 mt-4"> Сайт-визитка </h1>

            <p class="description pt-32">
Сайт-визитка — направлен в первую очередь на коммуникацию с основной аудиторией. Это место для размещения главной информации о товаре, услугах и что самое главное о самой компании. Зачастую необходимы фактические данные которые укажут на преимущества товаров и услуг компании-производителя. Такой сайт состоит из одной или нескольких страниц, но позволяет ознакомиться с важной информацией.
            </p>
            <div class="row mt-5">
                <div class="col-md-3">
                    <a class="btn btn-black" href="#contact">Сделать заказ</a>
                </div>
            </div>
        </div>
    </div>
</div>
