<div class="container current-service">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <img src="/img/Pechati.png" class="w-100">
        </div>
        <div class="col-lg-5 offset-lg-1">
            <h1 class="title mt-lg-0 mt-4"> Разработка этикетки </h1>

            <p class="description pt-32">
                Этикетка с момента своего появления стала неотъемлемой частью фирменного стиля компании и хорошим инструментом маркетинга. Она в удобном формате показывает всю философию компании, а также позволяет выделиться на фоне конкурентов. Существуют различные виды упаковок, их содержание зависит от нужд бренда и типа предлагаемого товара, а также целевой аудитории, на которую вы ориентируетесь.
            </p>
            <div class="row mt-5">
                <div class="col-md-3">
                    <a class="btn btn-black" href="#contact">Сделать заказ</a>
                </div>
            </div>
        </div>
    </div>
</div>
