<!--main page questions -->
<div data-aos="fade-up" class="container questions">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
             <?php
$useragent=$_SERVER['HTTP_USER_AGENT'];
    if(preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|
    iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|
    pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i',$useragent)||
    preg_match('/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|
    amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb
    |bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|
    ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|
    gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|
    i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |
    kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|
    me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|
    n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|
    pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|
    qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|
    sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|
    18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|
    vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|
    wonu|x700|yas\-|your|zeto|zte\-/i',substr($useragent,0,4)))
        {
            echo '<div align="center">
                <h1 class="title">Остались вопросы?</h1>
            </div>';
        }
    else
        {
            echo '<div>
                <h1 class="title">Остались вопросы?</h1>
            </div>';
        }
            ?>


            <!--Вопрос - ответ-->
            <div class="multi-question">
                <div class="row align-items-center">
                    <div class="col-10 mt-3">
                        <p class="h-100 question-text">
                        Что такое создание дизайна упаковки?
                        </p>
                    </div>
                    <div class="col-2 ml-auto">
                        <a  data-bs-toggle="collapse" href="#multiCollapseExample1" role="button"
                            aria-expanded="false"
                            aria-controls="multiCollapseExample1">
                            <i class="fas fa-plus btn-question magic-hover-none-cursor"></i>
                            <!--                                    <i class="fas fa-times btn-question"></i>-->
                        </a>
                    </div>
                </div>
                <div class="collapse multi-collapse" id="multiCollapseExample1">
                    <div>
                        <p class="question-text">
                        Это важный способ коммуникации с потребителем. Другие виды рекламы навязывают выбор покупателям, в то время как упаковка привлекает без раздражения и только в случае, когда человек заинтересован в товаре, таким образом, если человек сам выбрал товар из-за понравившейся упаковки, то он с большей вероятностью продолжит покупать товар, так как сам его выбрал
                        </p>
                    </div>
                </div>
            </div>

            <!--Вопрос - ответ-->
            <div class="multi-question">
                <div class="row align-items-center">
                    <div class="col-10 mt-3">
                        <p class="h-100 question-text">
                        Каковы главные цели разработки дизайна упаковки?
                        </p>
                    </div>
                    <div class="col-2 ml-auto">
                        <a  data-bs-toggle="collapse" href="#multiCollapseExample2" role="button"
                            aria-expanded="false"
                            aria-controls="multiCollapseExample2">
                            <i class="fas fa-plus btn-question magic-hover-none-cursor"></i>
                            <!--                                    <i class="fas fa-times btn-question"></i>-->
                        </a>
                    </div>
                </div>
                <div class="collapse multi-collapse" id="multiCollapseExample2">
                    <div>
                        <p class="question-text">
                        1) повышение идентификации товара среди конкурентов; 
                        <br>
                        2) охват новой аудитории; 
                        <br>
                        3) увеличить престиж компании и товара среди партнёров и покупателей; 
                        <br>
                        4) побуждение к совершению большего числа покупок.
                        </p>
                    </div>
                </div>
            </div>

            <!--Вопрос - ответ-->
            <div class="multi-question">
                <div class="row align-items-center">
                    <div class="col-10 mt-3">
                        <p class="h-100 question-text">
                        Какова цена создания дизайна?
                        </p>
                    </div>
                    <div class="col-2 ml-auto">
                        <a  data-bs-toggle="collapse" href="#multiCollapseExample3" role="button"
                            aria-expanded="false"
                            aria-controls="multiCollapseExample3">
                            <i class="fas fa-plus btn-question magic-hover-none-cursor"></i>
                            <!--                                    <i class="fas fa-times btn-question"></i>-->
                        </a>
                    </div>
                </div>
                <div class="collapse multi-collapse" id="multiCollapseExample3">
                    <div>
                        <p class="question-text">
                        На данный вопрос нельзя ответить точной стоимостью, нужно больше информации о товаре. Однако цена формируется на основе направления продукта, объёма работы, времени на разработку и других факторах.
                        </p>
                    </div>
                </div>
            </div>

            <!--Вопрос - ответ-->
            <div class="multi-question">
                <div class="row align-items-center">
                    <div class="col-10 mt-3">
                        <p class="h-100 question-text">
                        Каковы основные принципы разработки дизайна упаковки?
                        </p>
                    </div>
                    <div class="col-2 ml-auto">
                        <a  data-bs-toggle="collapse" href="#multiCollapseExample4" role="button"
                            aria-expanded="false"
                            aria-controls="multiCollapseExample4">
                            <i class="fas fa-plus btn-question magic-hover-none-cursor"></i>
                            <!--                                    <i class="fas fa-times btn-question"></i>-->
                        </a>
                    </div>
                </div>
                <div class="collapse multi-collapse" id="multiCollapseExample4">
                    <div>
                        <p class="question-text">
                        Информативность — дизайн должен привлекать внимание и содержать главную информацию о товаре, а её в продуктах достаточно много и нужно граммотно расположить текст так, чтобы быть лучшими среди других товаров. 
                        <br>
                        Лаконичность — способность дизайна избежать лишних элементов и правильно расположить самое необходимое, не потеряв содержательности.
                        <br>
                         Привлечение внимания — продукт обязательно должен привлекать больше внимания чем продукция конкурентов, именно от этого будут зависеть продажи в долгосрочной перспективе.
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>