<div class="container current-service">
    <div class="row align-items-center landing-card ">
        <div class="col-lg-6">
            <img src="/img/Landing01.png" class="w-100">
        </div>
        <div class="col-lg-5 flex-grow-1">
            <h1 class="title mt-lg-0" style="font-size: 24px; font-weight: 700; margin: 0; line-height: 31px">Сайт-визитка</h1>
            <span class="landing-price">ОТ 500$</span>
            <p class="description" style="padding-top: 16px">
            Мобильная разработка это серьёзный инструмент современного бизнеса. Возможностями данного инструмента являются эффективная коммуникация со своей аудиторией и сбор её в более удобном чем соц. сети месте, возможность перенести на мобильные устройства интернет-магазин и тд. Пользователи смартфонов нередко остаются последней частью аудитории на которую владельцы определённых видов бизнеса обращают внимание, так что иметь приложение в среде, где у других его нет, является преимуществом.
            </p>
            <div class="row mt-5">
                <div class="col-md-2">
                    <a class="btn btn-black magic-hover magic-hover__square" href="#contact" role="button" style="transform: translate3d(0px, 0px, 0px);">
                    Отправить заявку <i class="fas fa-arrow-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
