<div class="container current-service">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <img src="/img/Online_store.png" class="w-100">
        </div>
        <div class="col-lg-5 offset-lg-1">
            <h1 class="title mt-lg-0 mt-4"> Интернет-магазин </h1>

            <p class="description pt-32">
                Интернет-магазин является одним из важнейших инструментов современного бизнеса, магазин в зависимости от размера и функционала будет полезен всем видам бизнеса. Большой процент розничных продаж находятся в онлайне и компании упускающие эти возможности реализации продукции рискуют остаться позади. Даже при наличии интернет-магазина нужно его постоянно развивать и дорабатывать, чтобы успевать отвечать на изменяющиеся запросы покупателей и рынка.
            </p>
            <div class="row mt-5">
                <div class="col-md-3">
                    <a class="btn btn-black" href="#contact">Сделать заказ</a>
                </div>
            </div>
        </div>
    </div>
</div>
