<div class="container current-service">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <img src="/img/Presentation.png" class="w-100">
        </div>
        <div class="col-lg-5 offset-lg-1">
            <h1 class="title mt-lg-0 mt-4"> Презентация </h1>

            <p class="description pt-32">
                Презентация — это возможность в визуальном формате подать рекламную и не только информацию. Такой вид подачи материала даёт значительные преимущества перед обычным видами передачи информации. Из преимуществ можно выделить использование графики, анимации и звукового сопровождения. Для презентации разрабатывается индивидуальный дизайн на основанный на фирменном стиле компании.
            </p>
            <div class="row mt-5">
                <div class="col-md-3">
                    <a class="btn btn-black" href="#contact">Сделать заказ</a>
                </div>
            </div>
        </div>
    </div>
</div>
