<div class="container current-service">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <img src="/img/Promo_site.png" class="w-100">
        </div>
        <div class="col-lg-5 offset-lg-1">
            <h1 class="title mt-lg-0 mt-4"> Промо-сайт </h1>

            <p class="description pt-32">
                Промо-сайт является — узконаправленным видом сайта, который в отличие от остальных видов сайтов направлен исключительно на эффективную продажу определённого вида товара или услуги с целью получить максимальную прибыль. Промо-сайт имеет сходства с лендингом, однако в данном случае контактные данные компании, другие товары с услугами не так важны, на первом месте основной товар.
            </p>
            <div class="row mt-5">
                <div class="col-md-3">
                    <a class="btn btn-black" href="#contact">Сделать заказ</a>
                </div>
            </div>
        </div>
    </div>
</div>
