<div class="container current-service">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <img src="/img/Semantica.png" class="w-100">
        </div>
        <div class="col-lg-5 offset-lg-1">
            <h1 class="title mt-lg-0 mt-4"> Семантическое ядро </h1>

            <p class="description pt-32">
                Семантическое ядро — это разделённые по категориям ключевые слова, связанные со структурой вашего сайта, которые происходят от запросов в интернете. По данным запросам пользователи находят нужные им вещи, сервис и информацию в поисковиках. Количество запросов формируется на основе популярности отрасли и от определённого вида товара.
            </p>
            <div class="row mt-5">
                <div class="col-md-3">
                    <a class="btn btn-black" href="#contact">Сделать заказ</a>
                </div>
            </div>
        </div>
    </div>
</div>
