<div class="container current-service">
    <div class="row align-items-center">
        <div class="col-lg-6">
            <img src="/img/SMM.png" class="w-100">
        </div>
        <div class="col-lg-5 offset-lg-1">
            <h1 class="title mt-lg-0 mt-4"> SMM продвижение </h1>

            <p class="description pt-32">
                SMM - это уникальное направление интернет-маркетинга, включающее в себя весь список возможностей продвижения и достижения целей в сфере маркетинга в социальных сетях. В данной отрасли есть разные виды проектов и способов их продвижения, однако главной целью остаётся продвижение компании, продажа товаров и улучшение лояльности к бренду у аудитории.
            </p>
            <div class="row mt-5">
                <div class="col-md-3">
                    <a class="btn btn-black" href="#contact">Сделать заказ</a>
                </div>
            </div>
        </div>
    </div>
</div>
