<div data-aos="fade-up" class="more">
    <div class="container">
        <div class="row" align="center">
            <div class="col-lg-6 offset-lg-3">
                <h1 class="title">Узнайте больше о нас</h1>
                <p class="description my-4">
                    Мы сделали более 100 проектов, помогая людям любить то, чем они пользуются
                </p>
                <div class="row pt-lg-5 pt-4" align="center">
                    <div class="col">
                        <a class="btn btn-black magic-hover magic-hover__square mx-3"
                           href="/services" role="button">Услуги</a>

                        <a class="btn btn-black magic-hover magic-hover__square my-lg-0 my-2"
                           href="/portfolio" role="button">Портфолио</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
