<?php
    include_once "components/google.phtml";
    include_once "components/yandex.phtml";
    include_once "components/navbar.phtml";

    include_once "components/article.phtml";
    include_once "components/more_articles.phtml";
    include_once "components/more.phtml";
    include_once "components/questions.phtml";
    include_once "components/more_details_about.phtml";

    include_once "components/footer.phtml";
