<div data-aos="fade-up" class="container this-article" id="read_blog">
    <div class="row">
        <p class="blog-date">
            {{post[0].data}}
        </p>
        <div class="col-lg-7">
            <h1 class="title">
                {{post[0].title}}
            </h1>
            <img :src=post[0].image class="w-100 mt-5">
            <p class="mt-5 description">
                {{post[0].description}}
            </p>
            <p class="mt-5 description">
                {{post[0].post}}
            </p>
        </div>

    </div>
</div>